credentials:
  usernames:
    '01':
      name: Xiangkun Hu
      role: annotator
      password: $2b$12$KgwVsk1IT4ss4AmVneCv8errpwMXI4xh5nt7qKg6OJwprqhJwxKRK # 123456
    '02':
      name: Chi Xue
      role: annotator
      password: $2b$12$KgwVsk1IT4ss4AmVneCv8errpwMXI4xh5nt7qKg6OJwprqhJwxKRK # 123456
cookie:
  expiry_days: 90
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - xiangkhu@amazon.com